# Generated by Django 4.2.15 on 2024-09-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_submission_allow_resubmission_submission_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('returned', 'Returned for redo'), ('graded', 'Graded')], default='pending', max_length=10),
        ),
    ]
