# Generated by Django 4.2.15 on 2024-09-18 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(related_name='homework_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
