# Generated by Django 4.2.15 on 2025-05-29 17:17

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_add_default_general_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(default=polls.models.get_default_subject, on_delete=django.db.models.deletion.CASCADE, to='polls.subject'),
        ),
    ]
