# Generated by Django 4.2.15 on 2025-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_submission_file_submissionfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='comments',
            new_name='comments_student',
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_teacher',
            field=models.TextField(blank=True, null=True),
        ),
    ]
